MDSRCS+= \
	bcopy_vsx.S \
	bcopy_resolver.c \
	memcpy_vsx.S \
	memcpy_resolver.c \
	memmove_vsx.S \
	memmove_resolver.c \
	strncpy_arch_2_05.S \
	strncpy.c \
	strncpy_resolver.c \
	strcpy_arch_2_05.S \
	strcpy.c \
	strcpy_resolver.c
