"""Pass-runner framework: apply passes, record diffs/refusals, stage outputs."""
from __future__ import annotations

import json
import shutil
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from .compile_db import coverage_report, default_flags, generate_compile_commands
from .differential import differential
from .ir_oracle import compare_ir
from .passes import passes_for_tiers
from .schema import PassResult, Refusal
from .unit import TranslationUnit

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "migration" / "clang_port"
STAGED = OUT / "staged"
CORPUS = Path(__file__).resolve().parent / "corpus"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def discover_sources(scopes: list[str], limit: int | None = None) -> list[Path]:
    files: list[Path] = []
    for scope in scopes:
        base = ROOT / "hbsd" / "src" / scope
        if not base.exists():
            continue
        for p in sorted(base.rglob("*.c")):
            if ".git" in p.parts:
                continue
            files.append(p)
    if limit is not None:
        files = files[:limit]
    return files


BANNER = """/* PBSD automated port from {orig}. Do not mark DONE without differential / IR oracle. */
/* Generated by tools/run_todo_passes.py — deterministic passes from todo.md */
#if defined(__cplusplus)
#include <cstddef>
#include <cstdlib>
#endif

"""


def run_passes_on_unit(
    unit: TranslationUnit,
    tiers: set[int] | None = None,
) -> tuple[TranslationUnit, list[Refusal], list[dict]]:
    refusals: list[Refusal] = []
    edit_log: list[dict] = []
    for p in passes_for_tiers(tiers):
        if not p.precondition(unit):
            refusals.append(
                Refusal(
                    file=unit.path,
                    line=1,
                    col=1,
                    pass_name=p.name,
                    reason_code="PRECONDITION_FAIL",
                    enclosing_function="<file>",
                    snippet="precondition failed",
                )
            )
            continue
        result: PassResult = p.apply(unit)
        unit.text = result.text
        refusals.extend(result.refusals)
        for e in result.edits:
            edit_log.append(asdict(e))
    return unit, refusals, edit_log


def stage_path_for(src: Path) -> Path:
    rel = src.relative_to(ROOT / "hbsd" / "src")
    return STAGED / rel.with_suffix(".cpp")


def process_file(
    src: Path,
    tiers: set[int] | None = None,
    do_ir: bool = False,
    do_diff: bool = False,
) -> dict:
    text = src.read_text(encoding="utf-8", errors="replace")
    rel = src.relative_to(ROOT).as_posix()
    unit = TranslationUnit(path=rel, text=text)
    unit, refusals, edits = run_passes_on_unit(unit, tiers)

    out_text = BANNER.format(orig=rel) + unit.text
    dest = stage_path_for(src)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(out_text, encoding="utf-8")

    # Side-by-side original copy for oracle
    orig_stage = dest.with_suffix(".c.orig")
    shutil.copy2(src, orig_stage)

    record = {
        "source": rel,
        "staged": dest.relative_to(ROOT).as_posix(),
        "edits": len(edits),
        "refusals": len(refusals),
        "edit_list": edits,
        "refusal_list": [r.to_dict() for r in refusals],
        "ir": None,
        "diff": None,
    }

    includes = default_flags(ROOT)
    # For IR/diff, prefer freestanding-ish files without heavy BSD headers
    heavy = any(
        x in text
        for x in (
            "capsicum",
            "sys/",
            "libcasper",
            "<err.h>",
            "caph_",
        )
    )
    if do_ir and not heavy and src.stat().st_size < 8000:
        record["ir"] = compare_ir(src, dest, include_flags=["-Wno-everything"])
    elif do_ir:
        record["ir"] = {"status": "skipped_heavy", "equal": False}

    if do_diff and not heavy and "main" in text and src.stat().st_size < 4000:
        # Only argv-only utilities; avoid programs that read stdin forever.
        record["diff"] = differential(
            src,
            dest,
            inputs=[[]],
            include_flags=["-Wno-everything"],
        )
    elif do_diff:
        record["diff"] = {"status": "skipped_heavy", "equal": False}

    return record


def run_corpus_tests() -> dict:
    """Golden-file smoke tests for Tier 1 transforms."""
    results = []
    corpus_dir = CORPUS
    if not corpus_dir.exists():
        return {"ok": False, "error": "corpus missing", "cases": []}
    for inp in sorted(corpus_dir.glob("*.c")):
        expected = inp.with_suffix(".expected")
        text = inp.read_text(encoding="utf-8")
        unit = TranslationUnit(path=inp.name, text=text)
        unit, refusals, edits = run_passes_on_unit(unit, tiers={1, 2, 3})
        got = unit.text
        if expected.exists():
            exp = expected.read_text(encoding="utf-8")
            # Compare ignoring trailing whitespace
            ok = got.strip() == exp.strip() or exp.strip() in got.strip()
            # Also accept if all expected markers present
            if not ok and expected.suffix == ".expected":
                markers = [
                    ln[2:].strip()
                    for ln in exp.splitlines()
                    if ln.startswith("@@")
                ]
                if markers:
                    ok = all(m in got for m in markers)
            results.append(
                {
                    "case": inp.name,
                    "ok": ok,
                    "edits": len(edits),
                    "refusals": len(refusals),
                }
            )
        else:
            # Write expected draft for first run
            expected.write_text(got, encoding="utf-8")
            results.append({"case": inp.name, "ok": True, "drafted_expected": True})
    ok = all(r.get("ok") for r in results) if results else False
    return {"ok": ok, "cases": results}


def run_clang_tidy_on_staged(limit: int | None = 80, fix: bool = True) -> dict:
    """Run clang-tidy-18 on staged .cpp (best-effort; no compile DB required)."""
    import shutil
    import subprocess

    tidy = shutil.which("clang-tidy-18") or shutil.which("clang-tidy")
    if not tidy:
        return {"skipped": True, "reason": "clang-tidy not found"}
    targets = sorted(STAGED.rglob("*.cpp"))
    if limit is not None:
        targets = targets[:limit]
    cfg = ROOT / "tools" / "clang_port" / "clang-tidy-port"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    if not cfg.exists():
        cfg.write_text(
            "---\n"
            "Checks: 'modernize-use-nullptr,modernize-use-override,modernize-use-using,"
            "cppcoreguidelines-no-malloc,bugprone-use-after-move'\n"
            "WarningsAsErrors: ''\n",
            encoding="utf-8",
        )
    results = []
    warning_sum = 0
    for t in targets:
        cmd = [tidy, f"-config-file={cfg}", str(t)]
        if fix:
            cmd.insert(1, "-fix")
        cmd.extend(
            [
                "--",
                "-std=c++23",
                "-Wno-everything",
                f"-I{ROOT / 'pbsd'}",
                f"-I{ROOT / 'hbsd' / 'src' / 'include'}",
            ]
        )
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=90)
            w = (proc.stdout + proc.stderr).count("warning:")
            warning_sum += w
            results.append(
                {
                    "path": t.relative_to(ROOT).as_posix(),
                    "rc": proc.returncode,
                    "warnings": w,
                }
            )
        except (subprocess.TimeoutExpired, OSError) as e:
            results.append({"path": str(t), "error": str(e)})
    out = {
        "skipped": False,
        "targets": len(targets),
        "warning_sum": warning_sum,
        "fix": fix,
        "results": results,
    }
    (OUT / "tidy_staged.json").write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    return out


def run_pipeline(
    scopes: list[str],
    limit: int | None = None,
    tiers: set[int] | None = None,
    do_ir: bool = True,
    do_diff: bool = True,
    files: list[Path] | None = None,
    do_tidy: bool = False,
    tidy_limit: int | None = 100,
) -> dict:
    OUT.mkdir(parents=True, exist_ok=True)
    # Reset side-channel jsonl for this run
    for side in ("pointer_kinds.jsonl", "global_clusters.jsonl", "proposals.jsonl"):
        p = OUT / side
        if p.exists():
            p.unlink()

    corpus = run_corpus_tests()
    sources = files if files is not None else discover_sources(scopes, limit)
    compile_commands = OUT / "compile_commands.json"
    generate_compile_commands(sources, compile_commands, ROOT)
    cov = coverage_report(sources, compile_commands)

    records = []
    all_refusals: list[dict] = []
    for src in sources:
        rec = process_file(src, tiers=tiers, do_ir=do_ir, do_diff=do_diff)
        records.append(rec)
        all_refusals.extend(rec["refusal_list"])

    # Dedupe refusals: same file/line/reason from stacked passes
    deduped: list[dict] = []
    seen_r: set[tuple] = set()
    for r in all_refusals:
        key = (r.get("file"), r.get("line"), r.get("reason_code"), (r.get("snippet") or "")[:60])
        if key in seen_r:
            continue
        seen_r.add(key)
        deduped.append(r)
    all_refusals = deduped

    tidy_report = None
    if do_tidy:
        tidy_report = run_clang_tidy_on_staged(limit=tidy_limit, fix=True)

    refusals_path = OUT / "refusals.jsonl"
    with refusals_path.open("w", encoding="utf-8") as f:
        for r in all_refusals:
            f.write(json.dumps(r) + "\n")

    # Reason histogram
    hist: dict[str, int] = {}
    for r in all_refusals:
        hist[r["reason_code"]] = hist.get(r["reason_code"], 0) + 1

    report = {
        "generated": utc_now(),
        "scopes": scopes,
        "files": len(sources),
        "staged_dir": STAGED.relative_to(ROOT).as_posix(),
        "compile_commands_coverage": cov,
        "corpus": corpus,
        "edits_total": sum(r["edits"] for r in records),
        "refusals_total": len(all_refusals),
        "reason_histogram": dict(sorted(hist.items(), key=lambda x: -x[1])),
        "ir_equal": sum(1 for r in records if (r.get("ir") or {}).get("equal")),
        "ir_ran": sum(
            1
            for r in records
            if (r.get("ir") or {}).get("status") in ("ok", "mismatch", "compile_fail")
        ),
        "diff_equal": sum(1 for r in records if (r.get("diff") or {}).get("equal")),
        "clang_tidy": tidy_report,
        "records": records,
    }
    (OUT / "pass_report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    # Markdown summary
    lines = [
        "# PBSD todo.md Pass Report",
        "",
        f"Generated: `{report['generated']}`",
        "",
        f"- Files processed: **{report['files']}**",
        f"- Edits applied: **{report['edits_total']}**",
        f"- Refusals (model queue only): **{report['refusals_total']}**",
        f"- compile_commands coverage: **{cov['coverage_pct']}%**",
        f"- Corpus OK: **{corpus.get('ok')}**",
        f"- IR equal: **{report['ir_equal']}** / ran **{report['ir_ran']}**",
        f"- Diff equal: **{report['diff_equal']}**",
    ]
    if tidy_report:
        if tidy_report.get("skipped"):
            lines.append(f"- clang-tidy: skipped ({tidy_report.get('reason')})")
        else:
            lines.append(
                f"- clang-tidy: targets={tidy_report.get('targets')} "
                f"warnings={tidy_report.get('warning_sum')} fix={tidy_report.get('fix')}"
            )
    lines += [
        "",
        "## Reason histogram (true refusals — not successful edits)",
        "",
        "| Reason | Count |",
        "|---|---:|",
    ]
    for k, v in report["reason_histogram"].items():
        lines.append(f"| `{k}` | {v} |")
    lines += [
        "",
        "## Top edited files",
        "",
        "| Edits | Refusals | File |",
        "|---:|---:|---|",
    ]
    top = sorted(records, key=lambda r: -r["edits"])[:30]
    for r in top:
        lines.append(f"| {r['edits']} | {r['refusals']} | `{r['source']}` |")
    lines += [
        "",
        "## Outputs",
        "",
        f"- Staged C++: `{STAGED}`",
        f"- Refusals: `{refusals_path}`",
        f"- Full JSON: `docs/migration/clang_port/pass_report.json`",
        "",
    ]
    md = "\n".join(lines) + "\n"
    (OUT / "todo_pass_report.md").write_text(md, encoding="utf-8")
    return report
