.include <bsd.init.mk>

FILES+=	freebsd-brand-rev.png freebsd-brand.png freebsd-install-brand-rev.png \
	freebsd-logo-rev.png

FILES+=	hardenedbsd-brand-rev.png hardenedbsd-logo-rev.png

FILESDIR=  /boot/images

.include <bsd.prog.mk>
