// PBSD -- mechanical C++23 port of stdc_first_leading_one.c, proven equivalent to
// the original C by LLVM IR comparison. Generated by pbsd.py.
module;
#include <limits.h>
#include <stdbit.h>

export module pbsd.lib.libc.stdbit.stdc_first_leading_one;

export namespace pbsd::lib::libc::stdbit::stdc_first_leading_one {

/*
 * Copyright (c) 2025 Robert Clausecker <fuz@FreeBSD.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */




unsigned int
stdc_first_leading_one_uc(unsigned char x)
{
	const int offset = UINT_WIDTH - UCHAR_WIDTH;

	if (x == 0)
		return (0);

	return (__builtin_clz(x << offset) + 1);
}

unsigned int
stdc_first_leading_one_us(unsigned short x)
{
	const int offset = UINT_WIDTH - USHRT_WIDTH;

	if (x == 0)
		return (0);

	return (__builtin_clz(x << offset) + 1);
}

unsigned int
stdc_first_leading_one_ui(unsigned int x)
{
	if (x == 0)
		return (0);

	return (__builtin_clz(x) + 1);
}

unsigned int
stdc_first_leading_one_ul(unsigned long x)
{
	if (x == 0)
		return (0);

	return (__builtin_clzl(x) + 1);
}

unsigned int
stdc_first_leading_one_ull(unsigned long long x)
{
	if (x == 0)
		return (0);

	return (__builtin_clzll(x) + 1);
}

}  // namespace pbsd::lib::libc::stdbit::stdc_first_leading_one
