# $FreeBSD$
#
# To enable this repository, instead of modifying or removing this file,
# create a /usr/local/etc/pkg/repos/HardenedBSD.conf file:
#
#   mkdir -p /usr/local/etc/pkg/repos
#   echo "HardenedBSD_Base_Tor: { enabled: yes }" > /usr/local/etc/pkg/repos/HardenedBSD.pkgbase.tor.conf
#

HardenedBSD_Base_Tor: {
  url: "http://koxjemlrdtl6kmlhxvl7vtn43icriwuanvocb32htwkdohra2bueasyd.onion/pkgbase/HardenedBSD/${ABI}",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: no
}
