# $FreeBSD$
#
# To enable this repository, instead of modifying or removing this file,
# create a /usr/local/etc/pkg/repos/HardenedBSD.conf file:
#
#   mkdir -p /usr/local/etc/pkg/repos
#   echo "HardenedBSD_Base: { enabled: yes }" > /usr/local/etc/pkg/repos/HardenedBSD.conf
#

HardenedBSD_Base: {
  url: "https://pkgbase.hardenedbsd.org/pkgbase/HardenedBSD/${ABI}",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: no
}
