// PBSD -- mechanical C++23 port of e_scalb.c, proven equivalent to
// the original C by LLVM IR comparison. Generated by pbsd.py.
module;
#include "math.h"
#include "math_private.h"

export module pbsd.lib.msun.src.e_scalb;

export namespace pbsd::lib::msun::src::e_scalb {


/*
 * ====================================================
 * Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
 *
 * Developed at SunSoft, a Sun Microsystems, Inc. business.
 * Permission to use, copy, modify, and distribute this
 * software is freely granted, provided that this notice 
 * is preserved.
 * ====================================================
 */

/*
 * scalb(x, fn) is provide for
 * passing various standard test suite. One 
 * should use scalbn() instead.
 */




#ifdef _SCALB_INT
double
scalb(double x, int fn)
#else
double
scalb(double x, double fn)
#endif
{
#ifdef _SCALB_INT
	return scalbn(x,fn);
#else
	if (isnan(x)||isnan(fn)) return x*fn;
	if (!finite(fn)) {
	    if(fn>0.0) return x*fn;
	    else       return x/(-fn);
	}
	if (rint(fn)!=fn) return (fn-fn)/(fn-fn);
	if ( fn > 65000.0) return scalbn(x, 65000);
	if (-fn > 65000.0) return scalbn(x,-65000);
	return scalbn(x,(int)fn);
#endif
}

}  // namespace pbsd::lib::msun::src::e_scalb
