# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Odin Loch <odin.loch@outlook.com.au>
"""Translation units the analyser is EXPECTED not to compile, and why.

A file that does not compile contributes no findings and looks, in every
total this sweep prints, exactly like a file that is clean. That is not a
hypothetical: libexec/rtld-elf/rtld.c came back ERROR on an unresolvable
`#include "notes.h"', and the defect it was hiding cost thirty-seven boot
runs. See docs/BUILDING.md.

So the ERROR set is inventoried. Every entry here is a decision on the
record; anything erroring that is NOT here is a new hole, and anything
here that has started compiling is a stale exemption. Both are reported
by analyze.py --check-errors.

Most entries are one of three honest reasons:

  not a translation unit   the file is #included by another (arch trap.c
                           includes subr_syscall.c) and has no business
                           compiling alone.
  option-gated             it needs a kernel option no config in this
                           tree sets - KASAN, KCSAN, KMSAN, TSLOG,
                           DEVICE_POLLING, COMPAT_43TTY.
  wrong architecture       32-bit-only or arch-private helpers, against
                           an amd64 sweep.

What is NOT an honest reason is "it needs a define nobody supplied".
sys/kern/subr_param.c was in this list for exactly that - MAXUSERS,
which config(8) fakes into an option - and it is not any more. That file
sets hz, maxfiles, nbuf and maxproc, and `hz' being clamped there is an
argument this repository's triage table leans on, made about a file the
analyser had never read. One -D and it compiles.
"""
from __future__ import annotations

EXPECTED = {
    # not a translation unit: #included by another file
    "sys/kern/kern_ctf.c":          "#included by kern_linker.c",
    "sys/kern/subr_syscall.c":      "#included by each arch's trap.c",
    "sys/kern/systrace_args.c":     "generated, #included by the dtrace glue",
    "sys/kern/subr_busdma_bounce.c": "#included by each arch's busdma",
    "sys/kern/subr_devmap.c":       "arch-private, #included where used",
    "sys/kern/subr_sfbuf.c":        "arch-private sf_buf helpers",

    # The C start-up's per-architecture IRELATIVE handler. Each is
    # `#include "reloc.c"' inside libc_start1.c, after that file has
    # declared __rela_iplt_start and picked Elf_Rela or Elf_Rel from
    # CRT_IRELOC_RELA/REL. Alone they see no <sys/elf.h> and no
    # <sys/types.h>, which is why the errors are `unknown type name
    # u_int' and an Elf_Addr that parsed as a function declaration.
    # libc_start1.c itself compiles now, and did not before this list
    # was written: the first C every process runs after the run-time
    # linker, never analysed once.
    "lib/libc/csu/amd64/reloc.c":     "#included by libc_start1.c",
    "lib/libc/csu/aarch64/reloc.c":   "#included by libc_start1.c",
    "lib/libc/csu/i386/reloc.c":      "#included by libc_start1.c",
    "lib/libc/csu/powerpc64/reloc.c": "#included by libc_start1.c",
    "lib/libc/csu/riscv/reloc.c":     "#included by libc_start1.c",

    # upstream SoftFloat's own benchmark harness, with a K&R main().
    # softfloat/Makefile.inc's SRCS does not name it and no libc links
    # it; softfloat.txt describes it as the timing program.
    "lib/libc/softfloat/timesoftfloat.c": "upstream's benchmark, not in SRCS",

    # rpcgen output. include/rpcsvc/Makefile runs rpcgen over yp.x,
    # nis.x and key_prot.x during buildworld; the .h files do not exist
    # in a source tree and there is nothing to point an -I at.
    "lib/libc/yp/xdryp.c":            "wants rpcsvc/yp.h, generated by rpcgen",
    "lib/libc/yp/yplib.c":            "wants rpcsvc/yp.h, generated by rpcgen",
    "lib/libc/rpc/getpublickey.c":    "wants rpc/key_prot.h, from rpcgen",
    "lib/libc/rpc/key_call.c":        "wants rpc/key_prot.h, from rpcgen",
    "lib/libc/rpc/auth_des.c":        "wants rpcsvc/nis.h, from rpcgen",
    "lib/libc/rpc/auth_time.c":       "wants rpcsvc/nis.h, from rpcgen",
    "lib/libc/rpc/key_prot_xdr.c":    "wants rpc/key_prot.h, from rpcgen",
    "lib/libc/rpc/crypt_client.c":    "wants rpcsvc/crypt.h, from rpcgen",

    # option-gated: no kernel config in this tree sets these
    "sys/kern/subr_asan.c":         "needs option KASAN",
    "sys/kern/subr_csan.c":         "needs option KCSAN",
    "sys/kern/subr_msan.c":         "needs option KMSAN",
    "sys/kern/kern_tslog.c":        "needs option TSLOG",
    "sys/kern/kern_poll.c":         "needs option DEVICE_POLLING",
    "sys/kern/tty_compat.c":        "needs option COMPAT_43TTY",

    # wrong architecture for an amd64 sweep
    "sys/kern/subr_atomic64.c":     "32-bit archs only",
    "sys/kern/subr_intr.c":         "needs machine/intr.h, which amd64 has not",
    "sys/powerpc/ofw/ofw_machdep.c": "wants powerpc's <fdt.h>, absent on amd64",

    # net80211
    "sys/net80211/ieee80211_alq.c": "needs option IEEE80211_ALQ",

    # security
    "sys/security/audit/audit_dtrace.c":
        "needs the opensolaris compat headers, i.e. option KDTRACE_HOOKS",
    "sys/hardenedbsd/hbsd_pax_SKEL.c":
        "a template, in no sys/conf/files line - see the note below",

    # NOT an honest entry. Listed so the gate is truthful about what it
    # sees, not so the problem is filed away: this one is a DEFECT.
    #
    # sys/conf/files:5299 builds it under `optional mac_grantbylabel',
    # and it does not compile, because its mac_policy_ops initialiser
    # names .mpo_proc_check_resource and struct mac_policy_ops has no
    # such member - the KPI has _debug, _sched, _signal and _wait. The
    # only two references to the name in the whole tree are this file's
    # own function and this initialiser, and upstream HardenedBSD is
    # identical, so `options mac_grantbylabel' has never built in either
    # tree. docs/security/UB_FINDINGS.md has the analysis; it needs a
    # decision that is not a mechanical fix.
    "sys/security/mac_grantbylabel/mac_grantbylabel.c":
        "BROKEN: registers a MAC entry point that does not exist",

    # libexec/rtld-elf. The other nine translation units in this
    # directory compiled for the first time when the rtld's own include
    # flags were supplied - see includes.py - and riscv/reloc.c reported
    # a finding immediately. These six are what is left.
    "libexec/rtld-elf/aarch64/reloc.c":   "another architecture's relocations",
    "libexec/rtld-elf/arm/reloc.c":       "another architecture's relocations",
    "libexec/rtld-elf/powerpc/reloc.c":   "another architecture's relocations",
    "libexec/rtld-elf/powerpc64/reloc.c": "another architecture's relocations",
    "libexec/rtld-elf/tests/parse_integer_test.c":
        "#includes parse_integer_func.c, which the test Makefile stages",
    "libexec/rtld-elf/tests/target/target.c":
        "#includes pythagoras.h from a sibling test library",

    # The DPAA ethernet. sys/powerpc/conf/dpaa/config.dpaa is a
    # `makeoptions DPAA_COMPILE_CMD=...' twenty-one -I long, and
    # files.dpaa builds every NCSW source through it; reading that made
    # 55 of these 66 translation units analysable for the first time.
    # These eleven are the remainder, and they are a fourth honest
    # reason:
    #
    #   not built   vendored with the rest of NXP's NetCommSw drop and
    #               named by no files*, no module Makefile and no other
    #               source in the tree. FreeBSD's DPAA port never took
    #               the mEMAC MAC, the MACSEC block, the storage-profile
    #               helper or the frame replicator.
    #
    # If any of them is ever wired into files.dpaa this list is what
    # says so: --check-errors fails on an entry that starts compiling.
    "sys/contrib/ncsw/Peripherals/FM/MAC/fman_crc32.c":
        "not built: no files* or Makefile names it",
    "sys/contrib/ncsw/Peripherals/FM/MAC/fman_memac.c":
        "not built: the mEMAC MAC is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MAC/fman_memac_mii_acc.c":
        "not built: the mEMAC MAC is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MAC/memac.c":
        "not built: the mEMAC MAC is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MAC/memac_mii_acc.c":
        "not built: the mEMAC MAC is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MACSEC/fm_macsec.c":
        "not built: the MACSEC block is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MACSEC/fm_macsec_guest.c":
        "not built: the MACSEC block is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MACSEC/fm_macsec_master.c":
        "not built: the MACSEC block is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/MACSEC/fm_macsec_secy.c":
        "not built: the MACSEC block is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/Pcd/fm_replic.c":
        "not built: the frame replicator is not in files.dpaa",
    "sys/contrib/ncsw/Peripherals/FM/SP/fman_sp.c":
        "not built: the storage-profile helper is not in files.dpaa",

    # libsodium, same fourth reason. sys/conf/files:5142-5200 names the
    # 77 sources the kernel takes - the stream ciphers, the one-time
    # auth, ed25519, AEGIS - and every one of them compiles. These 28
    # are the rest of upstream's library: password hashing, generic
    # hash, secretbox, libsodium's own randomness and its runtime init.
    # They want <assert.h>, <errno.h> and <stdlib.h> because they are
    # not kernel code and were never asked to be. (Its 72 test/default
    # programs are userland outright and are in includes.NOT_KERNEL,
    # with OpenZFS's tests/ and ACPICA's compiler/.)
    "sys/contrib/libsodium/src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c":
        "not built: sys/conf/files takes AEGIS and chacha20poly1305, not aesni AES-GCM",
    "sys/contrib/libsodium/src/libsodium/crypto_generichash/blake2b/ref/blake2b-ref.c":
        "not built: the kernel has no generichash consumer",
    "sys/contrib/libsodium/src/libsodium/crypto_generichash/blake2b/ref/generichash_blake2b.c":
        "not built: the kernel has no generichash consumer",
    "sys/contrib/libsodium/src/libsodium/crypto_kdf/blake2b/kdf_blake2b.c":
        "not built: the kernel has no libsodium KDF consumer",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2-core.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2-encoding.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-avx2.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-avx512f.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-ref.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-ssse3.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/argon2.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/pwhash_argon2i.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/argon2/pwhash_argon2id.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/crypto_pwhash.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/scrypt_platform.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c":
        "not built: argon2 and scrypt are userland password hashing",
    "sys/contrib/libsodium/src/libsodium/crypto_secretbox/crypto_secretbox_easy.c":
        "not built: no in-kernel secretbox consumer",
    "sys/contrib/libsodium/src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c":
        "not built: no in-kernel secretbox consumer",
    "sys/contrib/libsodium/src/libsodium/randombytes/nativeclient/randombytes_nativeclient.c":
        "not built: the kernel supplies its own randomness, sys/crypto/libsodium",
    "sys/contrib/libsodium/src/libsodium/randombytes/randombytes.c":
        "not built: the kernel supplies its own randomness, sys/crypto/libsodium",
    "sys/contrib/libsodium/src/libsodium/randombytes/salsa20/randombytes_salsa20_random.c":
        "not built: the kernel supplies its own randomness, sys/crypto/libsodium",
    "sys/contrib/libsodium/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c":
        "not built: the kernel supplies its own randomness, sys/crypto/libsodium",
    "sys/contrib/libsodium/src/libsodium/sodium/codecs.c":
        "not built: libsodium's own runtime init, allocator and version",
    "sys/contrib/libsodium/src/libsodium/sodium/core.c":
        "not built: libsodium's own runtime init, allocator and version",
    "sys/contrib/libsodium/src/libsodium/sodium/utils.c":
        "not built: libsodium's own runtime init, allocator and version",
    "sys/contrib/libsodium/src/libsodium/sodium/version.c":
        "not built: libsodium's own runtime init, allocator and version",

    # zstd, same reason again, and the one that had been hiding real
    # coverage: sys/conf/files:644-664 writes `compile-with ${ZSTD_C}'
    # WITHOUT quotes, which the files* reader had required. Supplying
    # ZSTD_C's three -I took the in-kernel zstd - zstdio(9) and the ZFS
    # compressor - from 7 OK / 51 ERROR to 27 / 31, and every one of the
    # 27 built sources now compiles. These fifteen are what upstream
    # ships beside them and FreeBSD does not take.
    "sys/contrib/zstd/lib/common/pool.c":
        "not built: the POSIX-thread worker pool, for zstdmt",
    "sys/contrib/zstd/lib/compress/zstdmt_compress.c":
        "not built: multi-threaded compression, userland only",
    "sys/contrib/zstd/lib/deprecated/zbuff_common.c":
        "not built: the deprecated ZBUFF API",
    "sys/contrib/zstd/lib/deprecated/zbuff_compress.c":
        "not built: the deprecated ZBUFF API",
    "sys/contrib/zstd/lib/dictBuilder/cover.c":
        "not built: dictionary training is a userland tool",
    "sys/contrib/zstd/lib/dictBuilder/divsufsort.c":
        "not built: dictionary training is a userland tool",
    "sys/contrib/zstd/lib/dictBuilder/fastcover.c":
        "not built: dictionary training is a userland tool",
    "sys/contrib/zstd/lib/dictBuilder/zdict.c":
        "not built: dictionary training is a userland tool",
    "sys/contrib/zstd/lib/legacy/zstd_v01.c":
        "not built: the v0.1 format decoder, ZSTD_LEGACY_SUPPORT",
    "sys/contrib/zstd/lib/legacy/zstd_v02.c":
        "not built: the v0.2 format decoder, ZSTD_LEGACY_SUPPORT",
    "sys/contrib/zstd/lib/legacy/zstd_v03.c":
        "not built: the v0.3 format decoder, ZSTD_LEGACY_SUPPORT",
    "sys/contrib/zstd/lib/legacy/zstd_v04.c":
        "not built: the v0.4 format decoder, ZSTD_LEGACY_SUPPORT",
    "sys/contrib/zstd/lib/legacy/zstd_v05.c":
        "not built: the v0.5 format decoder, ZSTD_LEGACY_SUPPORT",
    "sys/contrib/zstd/lib/legacy/zstd_v06.c":
        "not built: the v0.6 format decoder, ZSTD_LEGACY_SUPPORT",
    "sys/contrib/zstd/lib/legacy/zstd_v07.c":
        "not built: the v0.7 format decoder, ZSTD_LEGACY_SUPPORT",
}


def classify(errors: set[str]) -> tuple[list[str], list[str]]:
    """(unexpected, stale) for the ERROR set of one run.

    `stale' is only meaningful for files the run actually looked at, so
    the caller passes the scope's whole file set as `errors' being the
    ERROR subset of it - see analyze.py.
    """
    unexpected = sorted(e for e in errors if e not in EXPECTED)
    return unexpected, []
