// PBSD -- mechanical C++23 port of bcopywrap.c, proven equivalent to
// the original C by LLVM IR comparison. Generated by pbsd.py.
module;
#include "ipf.h"

export module pbsd.sbin.ipf.libipf.bcopywrap;

export namespace pbsd::sbin::ipf::libipf::bcopywrap {


/*
 * Copyright (C) 2012 by Darren Reed.
 *
 * See the IPFILTER.LICENCE file for details on licencing.
 *
 * $Id$
 */



int
bcopywrap(void *from, void *to, size_t size)
{
	bcopy((caddr_t)from, (caddr_t)to, size);
	return (0);
}


}  // namespace pbsd::sbin::ipf::libipf::bcopywrap
