add_library(pbsd_bifrost_virtio)
target_sources(pbsd_bifrost_virtio PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.virtio.cppm)
target_link_libraries(pbsd_bifrost_virtio PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_virtio PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_hypervisor)
target_sources(pbsd_bifrost_hypervisor PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.hypervisor.cppm)
target_link_libraries(pbsd_bifrost_hypervisor PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_hypervisor PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_nested)
target_sources(pbsd_bifrost_nested PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.nested.cppm)
target_link_libraries(pbsd_bifrost_nested PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_nested PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_ept)
target_sources(pbsd_bifrost_ept PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.ept.cppm)
target_link_libraries(pbsd_bifrost_ept PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_ept PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_vmcb)
target_sources(pbsd_bifrost_vmcb PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vmcb.cppm)
target_link_libraries(pbsd_bifrost_vmcb PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vmcb PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_vmcs)
target_sources(pbsd_bifrost_vmcs PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vmcs.cppm)
target_link_libraries(pbsd_bifrost_vmcs PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vmcs PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_npt)
target_sources(pbsd_bifrost_npt PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.npt.cppm)
target_link_libraries(pbsd_bifrost_npt PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_npt PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_ioapic)
target_sources(pbsd_bifrost_ioapic PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.ioapic.cppm)
target_link_libraries(pbsd_bifrost_ioapic PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_ioapic PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_lapic)
target_sources(pbsd_bifrost_lapic PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.lapic.cppm)
target_link_libraries(pbsd_bifrost_lapic PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_lapic PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_vpid)
target_sources(pbsd_bifrost_vpid PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vpid.cppm)
target_link_libraries(pbsd_bifrost_vpid PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vpid PUBLIC ${PBSD_FS_CXX})

add_library(pbsd_bifrost_exit)
target_sources(pbsd_bifrost_exit PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.exit.cppm)
target_link_libraries(pbsd_bifrost_exit PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_exit PUBLIC ${PBSD_FS_CXX})

if(NOT TARGET pbsd_bifrost_tlb)
add_library(pbsd_bifrost_tlb)
target_sources(pbsd_bifrost_tlb PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.tlb.cppm)
target_link_libraries(pbsd_bifrost_tlb PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_tlb PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_msr_bitmap)
add_library(pbsd_bifrost_msr_bitmap)
target_sources(pbsd_bifrost_msr_bitmap PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.msr_bitmap.cppm)
target_link_libraries(pbsd_bifrost_msr_bitmap PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_msr_bitmap PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vpmu)
add_library(pbsd_bifrost_vpmu)
target_sources(pbsd_bifrost_vpmu PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vpmu.cppm)
target_link_libraries(pbsd_bifrost_vpmu PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vpmu PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_hypercall)
add_library(pbsd_bifrost_hypercall)
target_sources(pbsd_bifrost_hypercall PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.hypercall.cppm)
target_link_libraries(pbsd_bifrost_hypercall PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_hypercall PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vmx_ctrl)
add_library(pbsd_bifrost_vmx_ctrl)
target_sources(pbsd_bifrost_vmx_ctrl PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vmx_ctrl.cppm)
target_link_libraries(pbsd_bifrost_vmx_ctrl PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vmx_ctrl PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vioapic)
add_library(pbsd_bifrost_vioapic)
target_sources(pbsd_bifrost_vioapic PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vioapic.cppm)
target_link_libraries(pbsd_bifrost_vioapic PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_vioapic PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vlapic)
add_library(pbsd_bifrost_vlapic)
target_sources(pbsd_bifrost_vlapic PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vlapic.cppm)
target_link_libraries(pbsd_bifrost_vlapic PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_vlapic PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_ioport)
add_library(pbsd_bifrost_ioport)
target_sources(pbsd_bifrost_ioport PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.ioport.cppm)
target_link_libraries(pbsd_bifrost_ioport PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_ioport PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_xsave)
add_library(pbsd_bifrost_xsave)
target_sources(pbsd_bifrost_xsave PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.xsave.cppm)
target_link_libraries(pbsd_bifrost_xsave PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_xsave PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vhpet)
add_library(pbsd_bifrost_vhpet)
target_sources(pbsd_bifrost_vhpet PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vhpet.cppm)
target_link_libraries(pbsd_bifrost_vhpet PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_vhpet PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vmx)
add_library(pbsd_bifrost_vmx)
target_sources(pbsd_bifrost_vmx PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vmx.cppm)
target_link_libraries(pbsd_bifrost_vmx PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vmx PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_svm)
add_library(pbsd_bifrost_svm)
target_sources(pbsd_bifrost_svm PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.svm.cppm)
target_link_libraries(pbsd_bifrost_svm PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_svm PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_inst_emul)
add_library(pbsd_bifrost_inst_emul)
target_sources(pbsd_bifrost_inst_emul PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.inst_emul.cppm)
target_link_libraries(pbsd_bifrost_inst_emul PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_inst_emul PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_snapshot)
add_library(pbsd_bifrost_snapshot)
target_sources(pbsd_bifrost_snapshot PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.snapshot.cppm)
target_link_libraries(pbsd_bifrost_snapshot PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_snapshot PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_iommu)
add_library(pbsd_bifrost_iommu)
target_sources(pbsd_bifrost_iommu PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.iommu.cppm)
target_link_libraries(pbsd_bifrost_iommu PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_iommu PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_pit)
add_library(pbsd_bifrost_pit)
target_sources(pbsd_bifrost_pit PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.pit.cppm)
target_link_libraries(pbsd_bifrost_pit PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_pit PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_pci_pass)
add_library(pbsd_bifrost_pci_pass)
target_sources(pbsd_bifrost_pci_pass PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.pci_pass.cppm)
target_link_libraries(pbsd_bifrost_pci_pass PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_pci_pass PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vga)
add_library(pbsd_bifrost_vga)
target_sources(pbsd_bifrost_vga PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vga.cppm)
target_link_libraries(pbsd_bifrost_vga PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_vga PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_rtc)
add_library(pbsd_bifrost_rtc)
target_sources(pbsd_bifrost_rtc PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.rtc.cppm)
target_link_libraries(pbsd_bifrost_rtc PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_rtc PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_intercept)
add_library(pbsd_bifrost_intercept)
target_sources(pbsd_bifrost_intercept PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.intercept.cppm)
target_link_libraries(pbsd_bifrost_intercept PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_intercept PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_memslot)
add_library(pbsd_bifrost_memslot)
target_sources(pbsd_bifrost_memslot PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.memslot.cppm)
target_link_libraries(pbsd_bifrost_memslot PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_memslot PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_irqchip)
add_library(pbsd_bifrost_irqchip)
target_sources(pbsd_bifrost_irqchip PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.irqchip.cppm)
target_link_libraries(pbsd_bifrost_irqchip PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_irqchip PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_migration)
add_library(pbsd_bifrost_migration)
target_sources(pbsd_bifrost_migration PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.migration.cppm)
target_link_libraries(pbsd_bifrost_migration PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_migration PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_timer)
add_library(pbsd_bifrost_timer)
target_sources(pbsd_bifrost_timer PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.timer.cppm)
target_link_libraries(pbsd_bifrost_timer PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_timer PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_apic_timer)
add_library(pbsd_bifrost_apic_timer)
target_sources(pbsd_bifrost_apic_timer PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.apic_timer.cppm)
target_link_libraries(pbsd_bifrost_apic_timer PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_apic_timer PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_gpa_pool)
add_library(pbsd_bifrost_gpa_pool)
target_sources(pbsd_bifrost_gpa_pool PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.gpa_pool.cppm)
target_link_libraries(pbsd_bifrost_gpa_pool PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_gpa_pool PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_msr_filter)
add_library(pbsd_bifrost_msr_filter)
target_sources(pbsd_bifrost_msr_filter PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.msr_filter.cppm)
target_link_libraries(pbsd_bifrost_msr_filter PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_msr_filter PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vmexit_reason)
add_library(pbsd_bifrost_vmexit_reason)
target_sources(pbsd_bifrost_vmexit_reason PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vmexit_reason.cppm)
target_link_libraries(pbsd_bifrost_vmexit_reason PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vmexit_reason PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_guest_mem)
add_library(pbsd_bifrost_guest_mem)
target_sources(pbsd_bifrost_guest_mem PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.guest_mem.cppm)
target_link_libraries(pbsd_bifrost_guest_mem PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_guest_mem PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_debug)
add_library(pbsd_bifrost_debug)
target_sources(pbsd_bifrost_debug PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.debug.cppm)
target_link_libraries(pbsd_bifrost_debug PUBLIC pbsd_core)
target_compile_options(pbsd_bifrost_debug PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_posted_intr)
add_library(pbsd_bifrost_posted_intr)
target_sources(pbsd_bifrost_posted_intr PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.posted_intr.cppm)
target_link_libraries(pbsd_bifrost_posted_intr PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_posted_intr PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_pml)
add_library(pbsd_bifrost_pml)
target_sources(pbsd_bifrost_pml PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.pml.cppm)
target_link_libraries(pbsd_bifrost_pml PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_pml PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vmfunc)
add_library(pbsd_bifrost_vmfunc)
target_sources(pbsd_bifrost_vmfunc PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vmfunc.cppm)
target_link_libraries(pbsd_bifrost_vmfunc PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vmfunc PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_unrestricted_guest)
add_library(pbsd_bifrost_unrestricted_guest)
target_sources(pbsd_bifrost_unrestricted_guest PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.unrestricted_guest.cppm)
target_link_libraries(pbsd_bifrost_unrestricted_guest PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_unrestricted_guest PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_cpuid)
add_library(pbsd_bifrost_cpuid)
target_sources(pbsd_bifrost_cpuid PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.cpuid.cppm)
target_link_libraries(pbsd_bifrost_cpuid PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_cpuid PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_mtrr)
add_library(pbsd_bifrost_mtrr)
target_sources(pbsd_bifrost_mtrr PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.mtrr.cppm)
target_link_libraries(pbsd_bifrost_mtrr PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_mtrr PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_cr_shadow)
add_library(pbsd_bifrost_cr_shadow)
target_sources(pbsd_bifrost_cr_shadow PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.cr_shadow.cppm)
target_link_libraries(pbsd_bifrost_cr_shadow PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_cr_shadow PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_dr_shadow)
add_library(pbsd_bifrost_dr_shadow)
target_sources(pbsd_bifrost_dr_shadow PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.dr_shadow.cppm)
target_link_libraries(pbsd_bifrost_dr_shadow PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_dr_shadow PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vnet)
add_library(pbsd_bifrost_vnet)
target_sources(pbsd_bifrost_vnet PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vnet.cppm)
target_link_libraries(pbsd_bifrost_vnet PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vnet PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vblk)
add_library(pbsd_bifrost_vblk)
target_sources(pbsd_bifrost_vblk PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vblk.cppm)
target_link_libraries(pbsd_bifrost_vblk PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vblk PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vconsole)
add_library(pbsd_bifrost_vconsole)
target_sources(pbsd_bifrost_vconsole PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vconsole.cppm)
target_link_libraries(pbsd_bifrost_vconsole PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vconsole PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vinput)
add_library(pbsd_bifrost_vinput)
target_sources(pbsd_bifrost_vinput PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vinput.cppm)
target_link_libraries(pbsd_bifrost_vinput PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vinput PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vserial)
add_library(pbsd_bifrost_vserial)
target_sources(pbsd_bifrost_vserial PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vserial.cppm)
target_link_libraries(pbsd_bifrost_vserial PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vserial PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_vballoon)
add_library(pbsd_bifrost_vballoon)
target_sources(pbsd_bifrost_vballoon PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.vballoon.cppm)
target_link_libraries(pbsd_bifrost_vballoon PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_vballoon PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_msi)
add_library(pbsd_bifrost_msi)
target_sources(pbsd_bifrost_msi PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.msi.cppm)
target_link_libraries(pbsd_bifrost_msi PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_msi PUBLIC ${PBSD_FS_CXX})
endif()

if(NOT TARGET pbsd_bifrost_msix)
add_library(pbsd_bifrost_msix)
target_sources(pbsd_bifrost_msix PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.msix.cppm)
target_link_libraries(pbsd_bifrost_msix PUBLIC pbsd_core pbsd_bifrost_hypervisor)
target_compile_options(pbsd_bifrost_msix PUBLIC ${PBSD_FS_CXX})
endif()

add_library(pbsd_bifrost)
target_sources(pbsd_bifrost PUBLIC FILE_SET CXX_MODULES FILES pbsd.bifrost.cppm)
target_link_libraries(pbsd_bifrost PUBLIC pbsd_handles pbsd_bifrost_virtio pbsd_bifrost_hypervisor
    pbsd_bifrost_nested pbsd_bifrost_ept pbsd_bifrost_vmcb
    pbsd_bifrost_vmcs pbsd_bifrost_npt
    pbsd_bifrost_ioapic pbsd_bifrost_lapic pbsd_bifrost_vpid pbsd_bifrost_exit
    pbsd_bifrost_tlb pbsd_bifrost_msr_bitmap pbsd_bifrost_vpmu
    pbsd_bifrost_hypercall
    pbsd_bifrost_vmx_ctrl pbsd_bifrost_vioapic pbsd_bifrost_vlapic
    pbsd_bifrost_ioport pbsd_bifrost_xsave pbsd_bifrost_vhpet
    pbsd_bifrost_vmx pbsd_bifrost_svm     pbsd_bifrost_inst_emul
    pbsd_bifrost_snapshot pbsd_bifrost_iommu
    pbsd_bifrost_pit pbsd_bifrost_pci_pass pbsd_bifrost_vga pbsd_bifrost_rtc
    pbsd_bifrost_intercept pbsd_bifrost_memslot pbsd_bifrost_irqchip
    pbsd_bifrost_migration pbsd_bifrost_timer pbsd_bifrost_apic_timer
    pbsd_bifrost_gpa_pool pbsd_bifrost_msr_filter pbsd_bifrost_vmexit_reason
    pbsd_bifrost_guest_mem pbsd_bifrost_debug pbsd_bifrost_posted_intr
    pbsd_bifrost_pml pbsd_bifrost_vmfunc pbsd_bifrost_unrestricted_guest
    pbsd_bifrost_cpuid pbsd_bifrost_mtrr pbsd_bifrost_cr_shadow pbsd_bifrost_dr_shadow
    pbsd_bifrost_vnet pbsd_bifrost_vblk pbsd_bifrost_vconsole pbsd_bifrost_vinput
    pbsd_bifrost_vserial pbsd_bifrost_vballoon pbsd_bifrost_msi pbsd_bifrost_msix)
target_compile_options(pbsd_bifrost PUBLIC ${PBSD_FS_CXX})
