// PBSD -- mechanical C++23 port of stdc_has_single_bit.c, proven equivalent to
// the original C by LLVM IR comparison. Generated by pbsd.py.
module;
#include <stdbit.h>
#include <stdbool.h>

export module pbsd.lib.libc.stdbit.stdc_has_single_bit;

export namespace pbsd::lib::libc::stdbit::stdc_has_single_bit {

/*
 * Copyright (c) 2025 Robert Clausecker <fuz@FreeBSD.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */




bool
stdc_has_single_bit_uc(unsigned char x)
{
	return (x != 0 && (x & (x - 1)) == 0);
}

bool
stdc_has_single_bit_us(unsigned short x)
{
	return (x != 0 && (x & (x - 1)) == 0);
}

bool
stdc_has_single_bit_ui(unsigned int x)
{
	return (x != 0 && (x & (x - 1)) == 0);
}

bool
stdc_has_single_bit_ul(unsigned long x)
{
	return (x != 0 && (x & (x - 1)) == 0);
}

bool
stdc_has_single_bit_ull(unsigned long long x)
{
	return (x != 0 && (x & (x - 1)) == 0);
}

}  // namespace pbsd::lib::libc::stdbit::stdc_has_single_bit
