#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Odin Loch <odin.loch@outlook.com.au>
# Wave 0 CI driver: clang-tidy L1 notes, SI harness, inventory scripts.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

echo "== ParanoidBSD Wave 0 analyser CI =="

# --- L1 clang-tidy (non-blocking notes) --------------------------------------
if command -v clang-tidy >/dev/null 2>&1; then
    if [[ -f compile_commands.json ]]; then
        echo "-- clang-tidy L1 (pbsd/, first 24 TUs) --"
        mapfile -t _tidy_targets < <(find pbsd -type f \( -name '*.cpp' -o -name '*.cppm' \) | sort | head -24)
        tidy_rc=0
        for f in "${_tidy_targets[@]}"; do
            clang-tidy -p "$ROOT" "$f" --quiet 2>/dev/null || tidy_rc=1
        done
        if [[ $tidy_rc -ne 0 ]]; then
            echo "clang-tidy: notes emitted (non-fatal in Wave 0)"
        else
            echo "clang-tidy: clean on sampled TUs"
        fi
    else
        echo "SKIP clang-tidy: compile_commands.json missing (run cmake -B build -S pbsd)"
    fi
else
    echo "SKIP clang-tidy: not installed"
fi

# --- SI harness (hosted CMake) -----------------------------------------------
# pbsd/CMakeLists.txt is generated by pbsd.py and currently defines a single
# target, `pbsd`. pbsd_si_harness and pbsd_cxx_hello_smoke do not exist in it,
# so asking for them aborted this script under `set -e` before the inventory
# ever ran. Build them when they are there, say so when they are not.
if command -v cmake >/dev/null 2>&1; then
    echo "-- SI harness (cmake + ctest) --"
    # pbsd/CMakeLists.txt sets CMAKE_CXX_SCAN_FOR_MODULES ON. GCC cannot
    # discover a C++20 import graph for CMake, so configuring with the default
    # compiler fails at Generate with "the compiler does not provide a way to
    # discover the import graph dependencies". pbsd-ci.yml passes clang++;
    # this script did not, which is why Wave 0 failed on every run.
    _cxx=()
    if command -v clang++ >/dev/null 2>&1; then
        _cxx=(-DCMAKE_CXX_COMPILER=clang++)
    else
        echo "WARN: clang++ not found; C++20 module scanning will fail under GCC."
    fi
    if command -v ninja >/dev/null 2>&1; then
        cmake -B build/wave0 -S pbsd -G Ninja -DCMAKE_BUILD_TYPE=Debug "${_cxx[@]}"
    else
        cmake -B build/wave0 -S pbsd -DCMAKE_BUILD_TYPE=Debug "${_cxx[@]}"
    fi
    _have=()
    for t in pbsd_si_harness pbsd_cxx_hello_smoke; do
        if cmake --build build/wave0 --target help 2>/dev/null | grep -qE "(^| )${t}([: ]|$)"; then
            _have+=("$t")
        fi
    done
    if [[ ${#_have[@]} -gt 0 ]]; then
        cmake --build build/wave0 --target "${_have[@]}"
        ctest --test-dir build/wave0 --output-on-failure -R 'si_harness|cxx_hello_smoke'
    else
        echo "SKIP SI harness: neither pbsd_si_harness nor pbsd_cxx_hello_smoke is a"
        echo "                 target in the generated pbsd/CMakeLists.txt."
    fi
else
    echo "SKIP SI harness: cmake not installed"
fi

# --- Inventory scripts -------------------------------------------------------
echo "-- C source inventory --"
python3 tools/inventory_c_sources.py
python3 tools/wave_purge_c_check.py

echo "== Wave 0 CI complete =="
