// PBSD -- mechanical C++23 port of stdc_first_trailing_one.c, proven equivalent to
// the original C by LLVM IR comparison. Generated by pbsd.py.
module;
#include <stdbit.h>

export module pbsd.lib.libc.stdbit.stdc_first_trailing_one;

export namespace pbsd::lib::libc::stdbit::stdc_first_trailing_one {

/*
 * Copyright (c) 2025 Robert Clausecker <fuz@FreeBSD.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */



unsigned int
stdc_first_trailing_one_uc(unsigned char x)
{
	if (x == 0)
		return (0);

	return (__builtin_ctz(x) + 1);
}

unsigned int
stdc_first_trailing_one_us(unsigned short x)
{
	if (x == 0)
		return (0);

	return (__builtin_ctz(x) + 1);
}

unsigned int
stdc_first_trailing_one_ui(unsigned int x)
{
	if (x == 0)
		return (0);

	return (__builtin_ctz(x) + 1);
}

unsigned int
stdc_first_trailing_one_ul(unsigned long x)
{
	if (x == 0)
		return (0);

	return (__builtin_ctzl(x) + 1);
}

unsigned int
stdc_first_trailing_one_ull(unsigned long long x)
{
	if (x == 0)
		return (0);

	return (__builtin_ctzll(x) + 1);
}

}  // namespace pbsd::lib::libc::stdbit::stdc_first_trailing_one
