#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Odin Loch <odin.loch@outlook.com.au>
"""Keep pbsd/CMakeLists.txt honest about which modules it builds.

The module list is an allowlist, not an inventory: 749 port.cppm exist and
675 are listed, and the 74 in the gap are excluded because nothing has
verified them. That is the right design and it is completely invisible -
the file's header says "generated by pbsd.py", pbsd.py is 67 lines and does
not write it, and the scripts that actually did are in tools/quarantine.

So the two things worth asserting:

  * every listed module exists. A listed file that is gone does not
    degrade, it fails the configure step.
  * the unlisted count is reported. It is the size of the backlog, and a
    number nobody prints is a number nobody moves.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

LISTED = re.compile(r"^\s+(\S+/port\.cppm)$", re.M)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", nargs="?", default="pbsd")
    ap.add_argument("--fail-on-missing", action="store_true")
    ap.add_argument("--list-unverified", action="store_true")
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    cmake = os.path.join(root, "CMakeLists.txt")
    if not os.path.isfile(cmake):
        print(f"no CMakeLists.txt under {args.root}", file=sys.stderr)
        return 2

    with open(cmake, "r", encoding="utf-8", errors="replace") as fh:
        listed = set(LISTED.findall(fh.read()))

    ondisk = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d != ".git"]
        if "port.cppm" in filenames:
            rel = os.path.relpath(os.path.join(dirpath, "port.cppm"), root)
            ondisk.add(rel.replace(os.sep, "/"))

    missing = sorted(listed - ondisk)
    unverified = sorted(ondisk - listed)

    print(f"modules listed in CMakeLists: {len(listed)}")
    print(f"port.cppm on disk:            {len(ondisk)}")
    print(f"listed but absent:            {len(missing)}")
    print(f"present but unverified:       {len(unverified)}")

    for p in missing:
        print(f"  MISSING {p}")
    if args.list_unverified:
        for p in unverified:
            print(f"  unverified {p}")

    if missing and args.fail_on_missing:
        print("\nA listed module that is not on disk fails cmake configure,")
        print("not the build - so it is worth catching before either.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
