#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Odin Loch <odin.loch@outlook.com.au>
"""CLI: run docs/plans/todo-passes.md automated C→C++23 port passes."""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT / "tools"))

from pbsd_passes.runner import run_corpus_tests, run_pipeline  # noqa: E402


def _pin_hash_seed() -> None:
    """Re-exec with PYTHONHASHSEED=0 so a run is reproducible.

    Some pass lets the iteration order of a set or dict of strings reach the
    output. With hash randomisation on that made the pipeline
    non-deterministic: two identical serial runs over hbsd/src/bin gave 3035
    and 3036 edits, disagreeing on bin/sh/arith_yacc.c, parser.c and var.c.
    A port that cannot be regenerated byte for byte cannot be reviewed or
    verified, so the seed is pinned rather than left to chance.

    Pinning also makes --jobs safe: workers inherit the seed, so a parallel
    run produces exactly what a serial one does.

    Set PBSD_NO_HASH_PIN=1 to skip this and observe the underlying variance.
    """
    if os.environ.get("PYTHONHASHSEED") == "0":
        return
    if os.environ.get("PBSD_NO_HASH_PIN") == "1":
        return
    env = dict(os.environ)
    env["PYTHONHASHSEED"] = "0"
    os.execve(sys.executable, [sys.executable, *sys.argv], env)


def main(argv: list[str] | None = None) -> int:
    _pin_hash_seed()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--scope",
        default="bin,usr.bin,sbin,lib,usr.sbin,libexec",
        help="Comma-separated under hbsd/src (add sys for kernel; huge)",
    )
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--skip", type=int, default=0, help="Skip first N discovered sources (resume)")
    ap.add_argument(
        "--append-proposals",
        action="store_true",
        help="Do not truncate proposals.jsonl (resume runs)",
    )
    ap.add_argument(
        "--keep-proposals",
        action="store_true",
        help="Alias: keep existing proposals.jsonl across this run",
    )
    ap.add_argument("--file", action="append", default=[], help="Specific file(s) relative to repo root")
    ap.add_argument("--tiers", default="0,1,2,3,4", help="Comma-separated tier numbers")
    ap.add_argument("--corpus-only", action="store_true")
    ap.add_argument("--skip-corpus", action="store_true", help="Skip golden corpus at pipeline start")
    ap.add_argument("--no-ir", action="store_true", help="Disable IR-equivalence oracle")
    ap.add_argument("--no-diff", action="store_true", help="Disable stdout/exit differential")
    ap.add_argument(
        "--ir-limit",
        type=int,
        default=25,
        help="Max eligible files for IR oracle (default 25; 0=off; -1=unlimited)",
    )
    ap.add_argument(
        "--diff-limit",
        type=int,
        default=10,
        help="Max eligible files for differential (default 10; 0=off; -1=unlimited)",
    )
    ap.add_argument(
        "--file-timeout",
        type=float,
        default=90.0,
        help="Per-file wall-clock timeout seconds (default 90)",
    )
    ap.add_argument(
        "--jobs",
        "-j",
        type=int,
        default=1,
        help="Worker processes (default 1); 0 uses every core. The passes "
             "are CPU-bound and single-threaded, so this is what lets a "
             "full-tree run finish.",
    )
    ap.add_argument("--all-passes", action="store_true", help="Alias: all tiers")
    ap.add_argument("--tidy", action="store_true", help="Run clang-tidy -fix on staged outputs")
    ap.add_argument("--tidy-limit", type=int, default=120)
    args = ap.parse_args(argv)

    if args.corpus_only:
        result = run_corpus_tests()
        print(json.dumps(result, indent=2))
        return 0 if result.get("ok") else 1

    tiers = {int(x) for x in args.tiers.split(",") if x.strip() != ""}
    if args.all_passes:
        tiers = {0, 1, 2, 3, 4}

    files = None
    if args.file:
        files = [(ROOT / f).resolve() for f in args.file]

    scopes = [s.strip() for s in args.scope.split(",") if s.strip()]

    def _lim(n: int) -> int | None:
        if n < 0:
            return None  # unlimited
        return n

    ir_limit = _lim(args.ir_limit)
    diff_limit = _lim(args.diff_limit)
    do_ir = not args.no_ir and (ir_limit is None or ir_limit > 0)
    do_diff = not args.no_diff and (diff_limit is None or diff_limit > 0)

    if args.jobs == 0:
        args.jobs = os.cpu_count() or 1
    args.jobs = max(1, args.jobs)

    report = run_pipeline(
        scopes=scopes,
        limit=args.limit,
        tiers=tiers,
        do_ir=do_ir,
        do_diff=do_diff,
        files=files,
        do_tidy=args.tidy,
        tidy_limit=args.tidy_limit,
        ir_limit=ir_limit if do_ir else 0,
        diff_limit=diff_limit if do_diff else 0,
        skip=args.skip,
        append_proposals=args.append_proposals or args.keep_proposals,
        skip_corpus=args.skip_corpus,
        reset_proposals=not (args.append_proposals or args.keep_proposals),
        file_timeout=args.file_timeout,
        jobs=args.jobs,
    )
    print(
        f"OK files={report['files']} edits={report['edits_total']} "
        f"refusals={report['refusals_total']} "
        f"ir={report['ir_equal']}/{report['ir_ran']} "
        f"diff={report['diff_equal']} "
        f"report=docs/migration/clang_port/todo_pass_report.md"
    )
    for reason, count in list(report["reason_histogram"].items())[:12]:
        print(f"  {reason}: {count}")
    if report.get("clang_tidy"):
        ct = report["clang_tidy"]
        print(
            f"  clang-tidy: targets={ct.get('targets')} "
            f"warnings={ct.get('warning_sum')} fix={ct.get('fix')}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
